[package]
name = "repr"
version = "0.1.0"
edition = "2021"
authors = ["Igor Kotrasiński <i.kotrasinsk@samsung.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
repr_macros = { path = "./macros" }
